//------------------------------------------------------------------------------
// <autogenerated>
//     
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'DataOption.cs'.
//
//     Template: Criteria.Generated.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;


 

namespace CFMData
{
    [Serializable]
    public partial class DataOptionCriteria 
    {
        private readonly Dictionary<string, object> _bag = new Dictionary<string, object>();
        
        #region Constructors

        public DataOptionCriteria(){}

        public DataOptionCriteria(System.Int32 dataOptionID)
        {
            DataOptionID = dataOptionID;
        }

        #endregion

        #region Public Properties

        #region Read-Write

        public System.Int32 DataOptionID
        {
            get { return GetValue<System.Int32>("DataOptionID"); }
            set { _bag["DataOptionID"] = value; }
        }

        public System.Int32 DataOptionTypeID
        {
            get { return GetValue<System.Int32>("DataOptionTypeID"); }
            set { _bag["DataOptionTypeID"] = value; }
        }

        public System.String Code
        {
            get { return GetValue<System.String>("Code"); }
            set { _bag["Code"] = value; }
        }

        public System.String DisplayValue
        {
            get { return GetValue<System.String>("DisplayValue"); }
            set { _bag["DisplayValue"] = value; }
        }

        public System.Int32? ParentID
        {
            get { return GetValue<System.Int32?>("ParentID"); }
            set { _bag["ParentID"] = value; }
        }

        public System.Int32 SortID
        {
            get { return GetValue<System.Int32>("SortID"); }
            set { _bag["SortID"] = value; }
        }

        public System.Boolean IsSystem
        {
            get { return GetValue<System.Boolean>("IsSystem"); }
            set { _bag["IsSystem"] = value; }
        }

        public System.String AdditionalConfigData
        {
            get { return GetValue<System.String>("AdditionalConfigData"); }
            set { _bag["AdditionalConfigData"] = value; }
        }

        public System.DateTime ActiveFrom
        {
            get { return GetValue<System.DateTime>("ActiveFrom"); }
            set { _bag["ActiveFrom"] = value; }
        }

        public System.DateTime? ActiveTo
        {
            get { return GetValue<System.DateTime?>("ActiveTo"); }
            set { _bag["ActiveTo"] = value; }
        }

        public System.DateTime CreatedOn
        {
            get { return GetValue<System.DateTime>("CreatedOn"); }
            set { _bag["CreatedOn"] = value; }
        }

        public System.Int32 CreatedBy
        {
            get { return GetValue<System.Int32>("CreatedBy"); }
            set { _bag["CreatedBy"] = value; }
        }

        public System.DateTime? UpdatedOn
        {
            get { return GetValue<System.DateTime?>("UpdatedOn"); }
            set { _bag["UpdatedOn"] = value; }
        }

        public System.Int32? UpdatedBy
        {
            get { return GetValue<System.Int32?>("UpdatedBy"); }
            set { _bag["UpdatedBy"] = value; }
        }

        #endregion
        
        #region Read-Only

        public bool CodeHasValue
        {
            get { return _bag.ContainsKey("Code"); }
        }

        public bool DisplayValueHasValue
        {
            get { return _bag.ContainsKey("DisplayValue"); }
        }

        public bool ParentIDHasValue
        {
            get { return _bag.ContainsKey("ParentID"); }
        }

        public bool AdditionalConfigDataHasValue
        {
            get { return _bag.ContainsKey("AdditionalConfigData"); }
        }

        public bool ActiveToHasValue
        {
            get { return _bag.ContainsKey("ActiveTo"); }
        }

        public bool UpdatedOnHasValue
        {
            get { return _bag.ContainsKey("UpdatedOn"); }
        }

        public bool UpdatedByHasValue
        {
            get { return _bag.ContainsKey("UpdatedBy"); }
        }

        /// <summary>
        /// Returns a list of all the modified properties and values.
        /// </summary>
        public Dictionary<string, object> StateBag
        {
            get
            {
                return _bag;
            }
        }

        /// <summary>
        /// Returns a list of all the modified properties and values.
        /// </summary>
        public string TableFullName
        {
            get
            {
                return "[dbo].[DataOption]";
            }
        }

        #endregion

        #endregion

        #region Overrides
        
        public  string ToString()
        {
            var result = String.Empty;
            var cancel = false;
            
            OnToString(ref result, ref cancel);
            if(cancel && !String.IsNullOrEmpty(result))
                return result;
            
            if (_bag.Count == 0)
                return "No criterion was specified.";

            foreach (KeyValuePair<string, object> key in _bag)
            {
                result += String.Format("[{0}] = '{1}' AND ", key.Key, key.Value);
            }

            return result.Remove(result.Length - 5, 5);
        }

        #endregion

        #region Private Methods
        private T GetValue<T>(string name)
        {
            object value;
            if (_bag.TryGetValue(name, out value))
                return (T) value;
        
            return default(T);
        }
        
        #endregion
        
        #region Partial Methods
        
        partial void OnToString(ref string result, ref bool cancel);
        
        #endregion
        
    }
}