//------------------------------------------------------------------------------
// <autogenerated>
//     
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'ApplicationRole.cs'.
//
//     Template path: DTO.Generated.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;


using System.Collections.Generic;
 
namespace CFMData
{
    [Serializable]
    public partial class ApplicationRoleDTO
    {
 #region Contructor(s)

        public ApplicationRoleDTO()
        { /* Require use of factory methods */ }

        #endregion

public ApplicationRole CopyDTO(ApplicationRole obj)
		{
			 
			obj.Name =this.Name ;
			obj.SystemRoleID =this.SystemRoleID ;
			obj.IsSystemRole =this.IsSystemRole ;
			obj.IsActive =this.IsActive ;
			return obj;
		}
        #region Properties

        public System.Int32 ApplicationRoleID { get; set; }
        public System.String Name { get; set; }
        public System.Int32 SystemRoleID { get; set; }
        public System.Boolean IsSystemRole { get; set; }
        public System.Boolean IsActive { get; set; }
        public System.Int32 CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Int32? UpdatedBy { get; set; }
        public System.DateTime? UpdatedOn { get; set; }

	// ZeroOrOneToMany
        public void LoadApplicationUsers(ApplicationRole obj)
        {
			if(obj.ApplicationUsers!=null)
			{
				_applicationUsersProperty=obj.ApplicationUsers.CurrentDTO;
			}
        }
	// ZeroOrOneToMany
	
        private List<ApplicationUserDTO>  _applicationUsersProperty=new List<ApplicationUserDTO>();
        public List<ApplicationUserDTO> ApplicationUsers
        {
			get
			{
				return  _applicationUsersProperty;
			}
			
		}
	
	
	
	
	
	
        private ApplicationUserDTO  _createdByApplicationUserProperty=null;
        public ApplicationUserDTO CreatedByApplicationUser
        {
			get
			{
				return  _createdByApplicationUserProperty;
			}
			set
			{
				 _createdByApplicationUserProperty=value;
			}
			
		}
        public void LoadCreatedByApplicationUser(ApplicationRole obj)
		{
			if(obj.CreatedByApplicationUser!=null)
			{
				_createdByApplicationUserProperty=obj.CreatedByApplicationUser.CurrentDTO;
			}
		}
		
		
        private ApplicationUserDTO  _updatedByApplicationUserProperty=null;
        public ApplicationUserDTO UpdatedByApplicationUser
        {
			get
			{
				return  _updatedByApplicationUserProperty;
			}
			set
			{
				 _updatedByApplicationUserProperty=value;
			}
			
		}
        public void LoadUpdatedByApplicationUser(ApplicationRole obj)
		{
			if(obj.UpdatedByApplicationUser!=null)
			{
				_updatedByApplicationUserProperty=obj.UpdatedByApplicationUser.CurrentDTO;
			}
		}
		
		
        private SystemRoleDTO  _systemRoleProperty=null;
        public SystemRoleDTO SystemRole
        {
			get
			{
				return  _systemRoleProperty;
			}
			set
			{
				 _systemRoleProperty=value;
			}
			
		}
        public void LoadSystemRole(ApplicationRole obj)
		{
			if(obj.SystemRole!=null)
			{
				_systemRoleProperty=obj.SystemRole.CurrentDTO;
			}
		}
		
		
			



        #endregion

    }
}