//------------------------------------------------------------------------------
// <autogenerated>
//     
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'BusinessEntity.cs'.
//
//     Template path: DTO.Generated.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;


using System.Collections.Generic;
 
namespace CFMData
{
    [Serializable]
    public partial class BusinessEntityDTO
    {
 #region Contructor(s)

        public BusinessEntityDTO()
        { /* Require use of factory methods */ }

        #endregion

public BusinessEntity CopyDTO(BusinessEntity obj)
		{
			 
			obj.Code =this.Code ;
			obj.Name =this.Name ;
			return obj;
		}
        #region Properties

        public System.Int32 BusinessEntityID { get; set; }
        public System.String Code { get; set; }
        public System.String Name { get; set; }

	// ZeroOrOneToMany
        public void LoadApplicationPermissions(BusinessEntity obj)
        {
			if(obj.ApplicationPermissions!=null)
			{
				_applicationPermissionsProperty=obj.ApplicationPermissions.CurrentDTO;
			}
        }
	// ZeroOrOneToMany
	
        private List<ApplicationPermissionDTO>  _applicationPermissionsProperty=new List<ApplicationPermissionDTO>();
        public List<ApplicationPermissionDTO> ApplicationPermissions
        {
			get
			{
				return  _applicationPermissionsProperty;
			}
			
		}
	// OneToMany
        public void LoadBusinessDivisions(BusinessEntity obj)
        {
			if(obj.BusinessDivisions!=null)
			{
				_businessDivisionsProperty=obj.BusinessDivisions.CurrentDTO;
			}
        }
	// OneToMany
	
        private List<BusinessDivisionDTO>  _businessDivisionsProperty=new List<BusinessDivisionDTO>();
        public List<BusinessDivisionDTO> BusinessDivisions
        {
			get
			{
				return  _businessDivisionsProperty;
			}
			
		}
	
	
	
	
	
	
			



        #endregion

    }
}