//------------------------------------------------------------------------------
// <autogenerated>
//     
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'DataOption.cs'.
//
//     Template: EditableRoot.DataAccess.StoredProcedures.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.SqlClient;
 using Dapper;

namespace CFMData
{
	public partial class DataOption
	{
    
		private DataOption DataPortal_Fetch(DataOptionCriteria criteria)
		{
 
			bool cancel = false;
			OnFetching(criteria, ref cancel);
			if (cancel) return null;
			using (var connection = new SqlConnection(ADOHelper.ConnectionString))
			{
				connection.Open();
				using (var command = new SqlCommand("[dbo].[spCFM_DataOption_Select]", connection))
				{
					command.CommandType = CommandType.StoredProcedure;
					command.Parameters.AddRange(ADOHelper.SqlParameters(criteria.StateBag));
                    command.Parameters.AddWithValue("@p_CodeHasValue", criteria.CodeHasValue);
                command.Parameters.AddWithValue("@p_DisplayValueHasValue", criteria.DisplayValueHasValue);
                command.Parameters.AddWithValue("@p_ParentIDHasValue", criteria.ParentIDHasValue);
                command.Parameters.AddWithValue("@p_AdditionalConfigDataHasValue", criteria.AdditionalConfigDataHasValue);
                command.Parameters.AddWithValue("@p_ActiveToHasValue", criteria.ActiveToHasValue);
                command.Parameters.AddWithValue("@p_UpdatedOnHasValue", criteria.UpdatedOnHasValue);
                command.Parameters.AddWithValue("@p_UpdatedByHasValue", criteria.UpdatedByHasValue);
					using(var reader = command.ExecuteReader())
					{
						var rowParser = reader.GetRowParser<DataOption>();                       
						if(reader.Read())
						{
							return GetDataOption(rowParser, reader);							
						}                            
						else
							throw new Exception(String.Format("The record was not found in 'dbo.DataOption' using the following criteria: {0}.", criteria));
					}
				}
			}
			OnFetched();
		}

       // [Transactional(TransactionalTypes.TransactionScope)]
		protected   void DataPortal_Insert()
		{
			bool cancel = false;
			OnInserting(ref cancel);
			if (cancel) return;
			using (var connection = new SqlConnection(ADOHelper.ConnectionString))
			{
				connection.Open();
				SqlTransaction trans = connection.BeginTransaction();
				try
				{
				
				using(var command = new SqlCommand("[dbo].[spCFM_DataOption_Insert]", connection,trans))
				{
					command.CommandType = CommandType.StoredProcedure;
					
          command.Parameters.AddWithValue("@p_DataOptionID", this.DataOptionID);
                command.Parameters["@p_DataOptionID"].Direction = ParameterDirection.Output;
                command.Parameters.AddWithValue("@p_DataOptionTypeID", this.DataOptionTypeID);
                command.Parameters.AddWithValue("@p_Code", ADOHelper.NullCheck(this.Code));
                command.Parameters.AddWithValue("@p_DisplayValue", ADOHelper.NullCheck(this.DisplayValue));
                command.Parameters.AddWithValue("@p_ParentID", ADOHelper.NullCheck(this.ParentID));
                command.Parameters.AddWithValue("@p_SortID", this.SortID);
                command.Parameters.AddWithValue("@p_IsSystem", this.IsSystem);
                command.Parameters.AddWithValue("@p_AdditionalConfigData", ADOHelper.NullCheck(this.AdditionalConfigData));
                command.Parameters.AddWithValue("@p_ActiveFrom", this.ActiveFrom);
                command.Parameters.AddWithValue("@p_ActiveTo", ADOHelper.NullCheck(this.ActiveTo));
                command.Parameters.AddWithValue("@p_CreatedOn", this.CreatedOn);
                command.Parameters.AddWithValue("@p_CreatedBy", this.CreatedBy);
                command.Parameters.AddWithValue("@p_UpdatedOn", ADOHelper.NullCheck(this.UpdatedOn));
                command.Parameters.AddWithValue("@p_UpdatedBy", ADOHelper.NullCheck(this.UpdatedBy));
					command.ExecuteNonQuery();                  
					_dataOptionIDProperty=(System.Int32)command.Parameters["@p_DataOptionID"].Value;
                    
				}
                
				UpdateChildren(this, connection,trans);
				
				trans.Commit();
			}
			catch(Exception ex)
			{
				trans.Rollback();
				throw;
			}
			
		}
			

			OnInserted();

		}

       // [Transactional(TransactionalTypes.TransactionScope)]
		protected   void DataPortal_Update()
		{
			bool cancel = false;
			OnUpdating(ref cancel);
			if (cancel) return;
			using (var connection = new SqlConnection(ADOHelper.ConnectionString))
			{
				connection.Open();
				SqlTransaction trans = connection.BeginTransaction();
				try
				{
				using(var command = new SqlCommand("[dbo].[spCFM_DataOption_Update]", connection,trans))
				{
					command.CommandType = CommandType.StoredProcedure;
					command.Parameters.AddWithValue("@p_DataOptionID", this.DataOptionID);
                command.Parameters.AddWithValue("@p_DataOptionTypeID", this.DataOptionTypeID);
                command.Parameters.AddWithValue("@p_Code", ADOHelper.NullCheck(this.Code));
                command.Parameters.AddWithValue("@p_DisplayValue", ADOHelper.NullCheck(this.DisplayValue));
                command.Parameters.AddWithValue("@p_ParentID", ADOHelper.NullCheck(this.ParentID));
                command.Parameters.AddWithValue("@p_SortID", this.SortID);
                command.Parameters.AddWithValue("@p_IsSystem", this.IsSystem);
                command.Parameters.AddWithValue("@p_AdditionalConfigData", ADOHelper.NullCheck(this.AdditionalConfigData));
                command.Parameters.AddWithValue("@p_ActiveFrom", this.ActiveFrom);
                command.Parameters.AddWithValue("@p_ActiveTo", ADOHelper.NullCheck(this.ActiveTo));
                command.Parameters.AddWithValue("@p_CreatedOn", this.CreatedOn);
                command.Parameters.AddWithValue("@p_CreatedBy", this.CreatedBy);
                command.Parameters.AddWithValue("@p_UpdatedOn", ADOHelper.NullCheck(this.UpdatedOn));
                command.Parameters.AddWithValue("@p_UpdatedBy", ADOHelper.NullCheck(this.UpdatedBy));
					//result: The number of rows changed, inserted, or deleted. -1 for select statements; 0 if no rows were affected, or the statement failed. 
					int result = command.ExecuteNonQuery();
					if (result == 0)
						throw new DBConcurrencyException("The entity is out of date on the client. Please update the entity and try again. This could also be thrown if the sql statement failed to execute.");

				}
				UpdateChildren(this, connection,trans);
				//FieldManager.UpdateChildren(this, connection);
				trans.Commit();
			}
			catch(Exception ex)
			{
				trans.Rollback();
				throw;
			}
			
		}

			OnUpdated();
		}
		protected   void UpdateChildren(DataOption parent,SqlConnection connection,SqlTransaction trans)
		{
		
		
			
			if(_stateAddressesPropertyChecked )
			{
				if(_stateAddressesProperty!=null)
				{
				
					foreach (Address obj in _stateAddressesProperty)
					{
						if (obj.IsNew)
						{
							obj.Child_Insert(parent, connection,trans);
						}
						else
						{
							if (obj.IsDirty ||  obj.IsChildDirty())
							{							
								obj.Child_Update(parent, connection,trans);
							}
						}
					}
				}
					
 
			}

			
			if(_countryAddressesPropertyChecked )
			{
				if(_countryAddressesProperty!=null)
				{
				
					foreach (Address obj in _countryAddressesProperty)
					{
						if (obj.IsNew)
						{
							obj.Child_Insert(parent, connection,trans);
						}
						else
						{
							if (obj.IsDirty ||  obj.IsChildDirty())
							{							
								obj.Child_Update(parent, connection,trans);
							}
						}
					}
				}
					
 
			}

			
			if(_applicationUsersPropertyChecked )
			{
				if(_applicationUsersProperty!=null)
				{
				
					foreach (ApplicationUser obj in _applicationUsersProperty)
					{
						if (obj.IsNew)
						{
							obj.Child_Insert(parent, connection,trans);
						}
						else
						{
							if (obj.IsDirty ||  obj.IsChildDirty())
							{							
								obj.Child_Update(parent, connection,trans);
							}
						}
					}
				}
					
 
			}

			
			if(_budgetLineCategoriesPropertyChecked )
			{
				if(_budgetLineCategoriesProperty!=null)
				{
				
					foreach (BudgetLineCategory obj in _budgetLineCategoriesProperty)
					{
						if (obj.IsNew)
						{
							obj.Child_Insert(parent, connection,trans);
						}
						else
						{
							if (obj.IsDirty ||  obj.IsChildDirty())
							{							
								obj.Child_Update(parent, connection,trans);
							}
						}
					}
				}
					
 
			}

			
			if(_clientsPropertyChecked )
			{
				if(_clientsProperty!=null)
				{
				
					foreach (Client obj in _clientsProperty)
					{
						if (obj.IsNew)
						{
							obj.Child_Insert(parent, connection,trans);
						}
						else
						{
							if (obj.IsDirty ||  obj.IsChildDirty())
							{							
								obj.Child_Update(parent, connection,trans);
							}
						}
					}
				}
					
 
			}

			
			if(_dataOptionTypesPropertyChecked )
			{
				if(_dataOptionTypesProperty!=null)
				{
				
					foreach (DataOptionType obj in _dataOptionTypesProperty)
					{
						if (obj.IsNew)
						{
							obj.Child_Insert(parent, connection,trans);
						}
						else
						{
							if (obj.IsDirty ||  obj.IsChildDirty())
							{							
								obj.Child_Update(parent, connection,trans);
							}
						}
					}
				}
					
 
			}

			
			if(_homesPropertyChecked )
			{
				if(_homesProperty!=null)
				{
				
					foreach (Home obj in _homesProperty)
					{
						if (obj.IsNew)
						{
							obj.Child_Insert(parent, connection,trans);
						}
						else
						{
							if (obj.IsDirty ||  obj.IsChildDirty())
							{							
								obj.Child_Update(parent, connection,trans);
							}
						}
					}
				}
					
 
			}


		}

		protected   void DataPortal_DeleteSelf()
		{
			bool cancel = false;
			OnSelfDeleting(ref cancel);
			if (cancel) return;            
			DataPortal_Delete(new DataOptionCriteria (DataOptionID));        
			OnSelfDeleted();
		}
        
		//[Transactional(TransactionalTypes.TransactionScope)]
		protected void DataPortal_Delete(DataOptionCriteria criteria)
		{
            bool cancel = false;
            OnDeleting(criteria, ref cancel);
            if (cancel) return;

            using (var connection = new SqlConnection(ADOHelper.ConnectionString))
            {
                connection.Open();
                using (var command = new SqlCommand("[dbo].[spCFM_DataOption_Delete]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
		
                    command.Parameters.AddRange(ADOHelper.SqlParameters(criteria.StateBag));

                    //result: The number of rows changed, inserted, or deleted. -1 for select statements; 0 if no rows were affected, or the statement failed. 
                    int result = command.ExecuteNonQuery();
                    if (result == 0)
                        throw new DBConcurrencyException("The entity is out of date on the client. Please update the entity and try again. This could also be thrown if the sql statement failed to execute.");
                }
            }

            OnDeleted();
		}
		
		 #region Child_Insert
        /// <summary>
        /// Inserts data into the data base using the information in the current 
        ///    CSLA editable child business object of type <see cref="DataOption"/> 
        /// </summary>
        /// <returns></returns>
        public void Child_Insert(SqlConnection connection,SqlTransaction trans)
        {
            bool cancel = false;
            OnChildInserting(connection, ref cancel,trans);
            if (cancel) return;

            if(connection.State != ConnectionState.Open) connection.Open();
            using(var command = new SqlCommand("[dbo].[spCFM_DataOption_Insert]", connection,trans))
            {
                command.CommandType = CommandType.StoredProcedure;
		
                command.Parameters.AddWithValue("@p_DataOptionID", this.DataOptionID);
                command.Parameters["@p_DataOptionID"].Direction = ParameterDirection.Output;
                command.Parameters.AddWithValue("@p_DataOptionTypeID", this.DataOptionTypeID);
                command.Parameters.AddWithValue("@p_Code", ADOHelper.NullCheck(this.Code));
                command.Parameters.AddWithValue("@p_DisplayValue", ADOHelper.NullCheck(this.DisplayValue));
                command.Parameters.AddWithValue("@p_ParentID", ADOHelper.NullCheck(this.ParentID));
                command.Parameters.AddWithValue("@p_SortID", this.SortID);
                command.Parameters.AddWithValue("@p_IsSystem", this.IsSystem);
                command.Parameters.AddWithValue("@p_AdditionalConfigData", ADOHelper.NullCheck(this.AdditionalConfigData));
                command.Parameters.AddWithValue("@p_ActiveFrom", this.ActiveFrom);
                command.Parameters.AddWithValue("@p_ActiveTo", ADOHelper.NullCheck(this.ActiveTo));
                command.Parameters.AddWithValue("@p_CreatedOn", this.CreatedOn);
                command.Parameters.AddWithValue("@p_CreatedBy", this.CreatedBy);
                command.Parameters.AddWithValue("@p_UpdatedOn", ADOHelper.NullCheck(this.UpdatedOn));
                command.Parameters.AddWithValue("@p_UpdatedBy", ADOHelper.NullCheck(this.UpdatedBy));

                command.ExecuteNonQuery();
               
                // Update identity primary key value.
                _dataOptionIDProperty=(System.Int32)command.Parameters["@p_DataOptionID"].Value;
            }

            UpdateChildren(this, connection,trans);

            OnChildInserted();
        }

        public void Child_Insert(ApplicationUser applicationUser, SqlConnection connection,SqlTransaction trans)
        {
            Child_Insert(applicationUser, null, connection,trans);
        }


        public void Child_Insert(DataOptionType dataOptionType, SqlConnection connection,SqlTransaction trans)
        {
            Child_Insert(null, dataOptionType, connection,trans);
        }


        public void Child_Insert(ApplicationUser applicationUser, DataOptionType dataOptionType, SqlConnection connection,SqlTransaction trans)
        {
            bool cancel = false;
            OnChildInserting(applicationUser, dataOptionType, connection, ref cancel,trans);
            if (cancel) return;

            if(connection.State != ConnectionState.Open) connection.Open();
            using(var command = new SqlCommand("[dbo].[spCFM_DataOption_Insert]", connection,trans))
            {
                command.CommandType = CommandType.StoredProcedure;
		
                command.Parameters.AddWithValue("@p_DataOptionID", this.DataOptionID);
                command.Parameters["@p_DataOptionID"].Direction = ParameterDirection.Output;
                command.Parameters.AddWithValue("@p_DataOptionTypeID", dataOptionType != null ? dataOptionType.DataOptionTypeID : this.DataOptionTypeID);
                command.Parameters.AddWithValue("@p_Code", ADOHelper.NullCheck(this.Code));
                command.Parameters.AddWithValue("@p_DisplayValue", ADOHelper.NullCheck(this.DisplayValue));
                command.Parameters.AddWithValue("@p_ParentID", ADOHelper.NullCheck(this.ParentID));
                command.Parameters.AddWithValue("@p_SortID", this.SortID);
                command.Parameters.AddWithValue("@p_IsSystem", this.IsSystem);
                command.Parameters.AddWithValue("@p_AdditionalConfigData", ADOHelper.NullCheck(this.AdditionalConfigData));
                command.Parameters.AddWithValue("@p_ActiveFrom", this.ActiveFrom);
                command.Parameters.AddWithValue("@p_ActiveTo", ADOHelper.NullCheck(this.ActiveTo));
                command.Parameters.AddWithValue("@p_CreatedOn", this.CreatedOn);
                command.Parameters.AddWithValue("@p_CreatedBy", applicationUser != null ? applicationUser.ApplicationUserID : this.CreatedBy);
                command.Parameters.AddWithValue("@p_UpdatedOn", ADOHelper.NullCheck(this.UpdatedOn));
                command.Parameters.AddWithValue("@p_UpdatedBy", ADOHelper.NullCheck(applicationUser != null ? applicationUser.ApplicationUserID : this.UpdatedBy));

                command.ExecuteNonQuery();
               
                // Update identity primary key value.
                _dataOptionIDProperty=(System.Int32)command.Parameters["@p_DataOptionID"].Value;

            // Update foreign keys values. This code will update the values passed in from the parent only if no errors occurred after executing the query.
            if(dataOptionType != null && dataOptionType.DataOptionTypeID != this.DataOptionTypeID)
                _dataOptionTypeIDProperty= dataOptionType.DataOptionTypeID;

            // Update foreign keys values. This code will update the values passed in from the parent only if no errors occurred after executing the query.
            if(applicationUser != null && applicationUser.ApplicationUserID != this.CreatedBy)
                _createdByProperty= applicationUser.ApplicationUserID;

            // Update foreign keys values. This code will update the values passed in from the parent only if no errors occurred after executing the query.
            if(applicationUser != null && applicationUser.ApplicationUserID != this.UpdatedBy)
                _updatedByProperty= applicationUser.ApplicationUserID;
            }
            
            // A child relationship exists on this Business Object but its type is not a child type (E.G. EditableChild). 
            // TODO: Please override OnChildInserted() and insert this child manually.
            // UpdateChildren(this, null, null, null, null, null, null, null, null, null, connection);

            OnChildInserted();
        }

        #endregion

        #region Child_Update

        /// <summary>
        /// Updates the corresponding record in the data base with the information in the current 
        ///    CSLA editable child business object of type <see cref="DataOption"/> 
        /// </summary>
        /// <returns></returns>
        public void Child_Update(SqlConnection connection,SqlTransaction trans)
        {
            bool cancel = false;
            OnChildUpdating(connection, ref cancel,trans);
            if (cancel) return;

            if(connection.State != ConnectionState.Open) connection.Open();
            using(var command = new SqlCommand("[dbo].[spCFM_DataOption_Update]", connection,trans))
            {
                command.CommandType = CommandType.StoredProcedure;
		
                command.Parameters.AddWithValue("@p_DataOptionID", this.DataOptionID);
                command.Parameters.AddWithValue("@p_DataOptionTypeID", this.DataOptionTypeID);
                command.Parameters.AddWithValue("@p_Code", ADOHelper.NullCheck(this.Code));
                command.Parameters.AddWithValue("@p_DisplayValue", ADOHelper.NullCheck(this.DisplayValue));
                command.Parameters.AddWithValue("@p_ParentID", ADOHelper.NullCheck(this.ParentID));
                command.Parameters.AddWithValue("@p_SortID", this.SortID);
                command.Parameters.AddWithValue("@p_IsSystem", this.IsSystem);
                command.Parameters.AddWithValue("@p_AdditionalConfigData", ADOHelper.NullCheck(this.AdditionalConfigData));
                command.Parameters.AddWithValue("@p_ActiveFrom", this.ActiveFrom);
                command.Parameters.AddWithValue("@p_ActiveTo", ADOHelper.NullCheck(this.ActiveTo));
                command.Parameters.AddWithValue("@p_CreatedOn", this.CreatedOn);
                command.Parameters.AddWithValue("@p_CreatedBy", this.CreatedBy);
                command.Parameters.AddWithValue("@p_UpdatedOn", ADOHelper.NullCheck(this.UpdatedOn));
                command.Parameters.AddWithValue("@p_UpdatedBy", ADOHelper.NullCheck(this.UpdatedBy));

                //result: The number of rows changed, inserted, or deleted. -1 for select statements; 0 if no rows were affected, or the statement failed. 
                int result = command.ExecuteNonQuery();
                if (result == 0)
                    throw new DBConcurrencyException("The entity is out of date on the client. Please update the entity and try again. This could also be thrown if the sql statement failed to execute.");
            }

            UpdateChildren(this, connection,trans);

            OnChildUpdated();
        }

        public void Child_Update(ApplicationUser applicationUser, SqlConnection connection,SqlTransaction trans)
        {
            Child_Update(applicationUser, null, connection,trans);
        }


        public void Child_Update(DataOptionType dataOptionType, SqlConnection connection,SqlTransaction trans)
        {
            Child_Update(null, dataOptionType, connection,trans);
        }

 
        public void Child_Update(ApplicationUser applicationUser, DataOptionType dataOptionType, SqlConnection connection,SqlTransaction trans)
        {
            bool cancel = false;
            OnChildUpdating(applicationUser, dataOptionType, connection, ref cancel,trans);
            if (cancel) return;

            if(connection.State != ConnectionState.Open) connection.Open();
            using(var command = new SqlCommand("[dbo].[spCFM_DataOption_Update]", connection,trans))
            {
                command.CommandType = CommandType.StoredProcedure;
		
                command.Parameters.AddWithValue("@p_DataOptionID", this.DataOptionID);
                command.Parameters.AddWithValue("@p_DataOptionTypeID", dataOptionType != null ? dataOptionType.DataOptionTypeID : this.DataOptionTypeID);
                command.Parameters.AddWithValue("@p_Code", ADOHelper.NullCheck(this.Code));
                command.Parameters.AddWithValue("@p_DisplayValue", ADOHelper.NullCheck(this.DisplayValue));
                command.Parameters.AddWithValue("@p_ParentID", ADOHelper.NullCheck(this.ParentID));
                command.Parameters.AddWithValue("@p_SortID", this.SortID);
                command.Parameters.AddWithValue("@p_IsSystem", this.IsSystem);
                command.Parameters.AddWithValue("@p_AdditionalConfigData", ADOHelper.NullCheck(this.AdditionalConfigData));
                command.Parameters.AddWithValue("@p_ActiveFrom", this.ActiveFrom);
                command.Parameters.AddWithValue("@p_ActiveTo", ADOHelper.NullCheck(this.ActiveTo));
                command.Parameters.AddWithValue("@p_CreatedOn", this.CreatedOn);
                command.Parameters.AddWithValue("@p_CreatedBy", applicationUser != null ? applicationUser.ApplicationUserID : this.CreatedBy);
                command.Parameters.AddWithValue("@p_UpdatedOn", ADOHelper.NullCheck(this.UpdatedOn));
                command.Parameters.AddWithValue("@p_UpdatedBy", ADOHelper.NullCheck(applicationUser != null ? applicationUser.ApplicationUserID : this.UpdatedBy));

                //result: The number of rows changed, inserted, or deleted. -1 for select statements; 0 if no rows were affected, or the statement failed. 
                int result = command.ExecuteNonQuery();
                if (result == 0)
                    throw new DBConcurrencyException("The entity is out of date on the client. Please update the entity and try again. This could also be thrown if the sql statement failed to execute.");

                // Update foreign keys values. This code will update the values passed in from the parent only if no errors occurred after executing the query.
                if(dataOptionType != null && dataOptionType.DataOptionTypeID != this.DataOptionTypeID)
                    _dataOptionTypeIDProperty= dataOptionType.DataOptionTypeID;

                // Update foreign keys values. This code will update the values passed in from the parent only if no errors occurred after executing the query.
                if(applicationUser != null && applicationUser.ApplicationUserID != this.CreatedBy)
                    _createdByProperty= applicationUser.ApplicationUserID;

                // Update foreign keys values. This code will update the values passed in from the parent only if no errors occurred after executing the query.
                if(applicationUser != null && applicationUser.ApplicationUserID != this.UpdatedBy)
                    _updatedByProperty= applicationUser.ApplicationUserID;
            }
            
            // A child relationship exists on this Business Object but its type is not a child type (E.G. EditableChild). 
            // TODO: Please override OnChildUpdated() and update this child manually.
            // UpdateChildren(this, null, null, null, null, null, null, null, null, null, connection);

            OnChildUpdated();
        }
        #endregion

        /// <summary>
        /// Deletes the corresponding record in the data base with the information in the current 
        ///    CSLA editable child business object of type <see cref="DataOption"/> 
        /// </summary>
        /// <returns></returns>
        private void Child_DeleteSelf(SqlConnection connection)
        {
            bool cancel = false;
            OnChildSelfDeleting(connection, ref cancel);
            if (cancel) return;
            
            //DataPortal_Delete(new DataOptionCriteria (DataOptionID), connection);
        
            OnChildSelfDeleted();
        }

        #region Map
		public void InitDTO()
		{
			  DataOptionDTO dt=new DataOptionDTO();
			dt.DataOptionID =this.DataOptionID ;
			dt.DataOptionTypeID =this.DataOptionTypeID ;
			dt.Code =this.Code ;
			dt.DisplayValue =this.DisplayValue ;
			dt.ParentID =this.ParentID ;
			dt.SortID =this.SortID ;
			dt.IsSystem =this.IsSystem ;
			dt.AdditionalConfigData =this.AdditionalConfigData ;
			dt.ActiveFrom =this.ActiveFrom ;
			dt.ActiveTo =this.ActiveTo ;
			dt.CreatedOn =this.CreatedOn ;
			dt.CreatedBy =this.CreatedBy ;
			dt.UpdatedOn =this.UpdatedOn ;
			dt.UpdatedBy =this.UpdatedBy ;
   //LoadProperty(_currentDto, dt);
  this.CurrentDTO = dt;

		}
		/*
        private void Map(SafeDataReader reader)
        {
            bool cancel = false;
            OnMapping(reader, ref cancel);
            if (cancel) return;

            using(BypassPropertyChecks)
            {
                LoadProperty(_dataOptionIDProperty, reader["DataOptionID"]);
                LoadProperty(_dataOptionTypeIDProperty, reader["DataOptionTypeID"]);
                LoadProperty(_codeProperty, reader["Code"]);
                LoadProperty(_displayValueProperty, reader["DisplayValue"]);
                LoadProperty(_parentIDProperty, reader["ParentID"]);
                LoadProperty(_sortIDProperty, reader["SortID"]);
                LoadProperty(_isSystemProperty, reader["IsSystem"]);
                LoadProperty(_additionalConfigDataProperty, reader["AdditionalConfigData"]);
                LoadProperty(_activeFromProperty, reader["ActiveFrom"]);
                LoadProperty(_activeToProperty, reader["ActiveTo"]);
                LoadProperty(_createdOnProperty, reader["CreatedOn"]);
                LoadProperty(_createdByProperty, reader["CreatedBy"]);
                LoadProperty(_updatedOnProperty, reader["UpdatedOn"]);
                LoadProperty(_updatedByProperty, reader["UpdatedBy"]);
            }	
			InitDTO();
            OnMapped();
        }
        
        private void Child_Fetch(SafeDataReader reader)
        {
            Map(reader);
        }
		*/

        #endregion
	}
}
 