//------------------------------------------------------------------------------
// <autogenerated>
//     
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'DataOptionTypeSort.cs'.
//
//     Template path: DTO.Generated.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;


using System.Collections.Generic;
 
namespace CFMData
{
    [Serializable]
    public partial class DataOptionTypeSortDTO
    {
 #region Contructor(s)

        public DataOptionTypeSortDTO()
        { /* Require use of factory methods */ }

        #endregion

public DataOptionTypeSort CopyDTO(DataOptionTypeSort obj)
		{
			 
			obj.DataOptionTypeSortID =this.DataOptionTypeSortID ;
			obj.Name =this.Name ;
			return obj;
		}
        #region Properties

        public System.Int32 DataOptionTypeSortID { get; set; }
        public System.String Name { get; set; }

	// ZeroOrOneToMany
        public void LoadDataOptionTypes(DataOptionTypeSort obj)
        {
			if(obj.DataOptionTypes!=null)
			{
				_dataOptionTypesProperty=obj.DataOptionTypes.CurrentDTO;
			}
        }
	// ZeroOrOneToMany
	
        private List<DataOptionTypeDTO>  _dataOptionTypesProperty=new List<DataOptionTypeDTO>();
        public List<DataOptionTypeDTO> DataOptionTypes
        {
			get
			{
				return  _dataOptionTypesProperty;
			}
			
		}
	
	
	
	
	
	
			



        #endregion

    }
}