//------------------------------------------------------------------------------
// <autogenerated>
//     
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'Address.cs'.
//
//     Template path: JS.DTO.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
export class  AddressDTO
{


     constructor(){}

addressID:number;
street:string;
suburb:string;
stateID:number;
countryID:number;
postCode:string;
isActive:boolean;
createdBy:number;
createdOn:Date;
updatedBy:number;
updatedOn:Date;
 
}