//------------------------------------------------------------------------------
// <autogenerated>
//     
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'BudgetType.cs'.
//
//     Template path: JS.DTO.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
export class  BudgetTypeDTO
{


     constructor(){}

budgetTypeID:number;
code:string;
name:string;
 
}