//------------------------------------------------------------------------------
// <autogenerated>
//     
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'ApplicationPermissionList.cs'.
//
//     Template: EditableRootList.Generated.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
 
namespace CFMData
{
    [Serializable]
    public partial class ApplicationPermissionList : List< ApplicationPermission>
    {    
        private List<ApplicationPermissionDTO> _currentDto =null; 
        public List<ApplicationPermissionDTO> CurrentDTO
        {
            get 
            {
                if (_currentDto==null)
                {
                    _currentDto=new List<ApplicationPermissionDTO>();
                    foreach (ApplicationPermission entity in this)
                    {
                        _currentDto.Add(entity.CurrentDTO);
                    }
                }
                return _currentDto;
			}
            
        }
        #region Contructor(s)

        public ApplicationPermissionList()
        { 
       //     AllowNew = true;
        }

        #endregion

       

        #region Synchronous Factory Methods 

        /// <summary>
        /// Creates a new object of type <see cref="ApplicationPermissionList"/>. 
        /// </summary>
        /// <returns>Returns a newly instantiated collection of type <see cref="ApplicationPermissionList"/>.</returns>
        public static ApplicationPermissionList NewList()
        {
            return new ApplicationPermissionList();
        }      

        /// <summary>
        /// Returns a <see cref="ApplicationPermissionList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="applicationPermissionID">No additional detail available.</param>
        /// <returns>A <see cref="ApplicationPermissionList"/> object of the specified criteria.</returns>
        public static ApplicationPermissionList GetByApplicationPermissionID(System.Int32 applicationPermissionID)
        {
            var criteria = new ApplicationPermissionCriteria{ApplicationPermissionID = applicationPermissionID};
            
            
          return  new ApplicationPermissionList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="ApplicationPermissionList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="createdBy">No additional detail available.</param>
        /// <returns>A <see cref="ApplicationPermissionList"/> object of the specified criteria.</returns>
        public static ApplicationPermissionList GetByCreatedBy(System.Int32 createdBy)
        {
            var criteria = new ApplicationPermissionCriteria{CreatedBy = createdBy};
            
            
          return  new ApplicationPermissionList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="ApplicationPermissionList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="updatedBy">No additional detail available.</param>
        /// <returns>A <see cref="ApplicationPermissionList"/> object of the specified criteria.</returns>
        public static ApplicationPermissionList GetByUpdatedBy(System.Int32? updatedBy)
        {
            var criteria = new ApplicationPermissionCriteria{};
                            if(updatedBy.HasValue) criteria.UpdatedBy = updatedBy.Value;
            
          return  new ApplicationPermissionList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="ApplicationPermissionList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="businessAreaID">No additional detail available.</param>
        /// <returns>A <see cref="ApplicationPermissionList"/> object of the specified criteria.</returns>
        public static ApplicationPermissionList GetByBusinessAreaID(System.Int32? businessAreaID)
        {
            var criteria = new ApplicationPermissionCriteria{};
                            if(businessAreaID.HasValue) criteria.BusinessAreaID = businessAreaID.Value;
            
          return  new ApplicationPermissionList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="ApplicationPermissionList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="businessDivisionID">No additional detail available.</param>
        /// <returns>A <see cref="ApplicationPermissionList"/> object of the specified criteria.</returns>
        public static ApplicationPermissionList GetByBusinessDivisionID(System.Int32? businessDivisionID)
        {
            var criteria = new ApplicationPermissionCriteria{};
                            if(businessDivisionID.HasValue) criteria.BusinessDivisionID = businessDivisionID.Value;
            
          return  new ApplicationPermissionList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="ApplicationPermissionList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="businessEntityID">No additional detail available.</param>
        /// <returns>A <see cref="ApplicationPermissionList"/> object of the specified criteria.</returns>
        public static ApplicationPermissionList GetByBusinessEntityID(System.Int32? businessEntityID)
        {
            var criteria = new ApplicationPermissionCriteria{};
                            if(businessEntityID.HasValue) criteria.BusinessEntityID = businessEntityID.Value;
            
          return  new ApplicationPermissionList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="ApplicationPermissionList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="clientID">No additional detail available.</param>
        /// <returns>A <see cref="ApplicationPermissionList"/> object of the specified criteria.</returns>
        public static ApplicationPermissionList GetByClientID(System.Int32? clientID)
        {
            var criteria = new ApplicationPermissionCriteria{};
                            if(clientID.HasValue) criteria.ClientID = clientID.Value;
            
          return  new ApplicationPermissionList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="ApplicationPermissionList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="homeID">No additional detail available.</param>
        /// <returns>A <see cref="ApplicationPermissionList"/> object of the specified criteria.</returns>
        public static ApplicationPermissionList GetByHomeID(System.Int32? homeID)
        {
            var criteria = new ApplicationPermissionCriteria{};
                            if(homeID.HasValue) criteria.HomeID = homeID.Value;
            
          return  new ApplicationPermissionList().DataPortal_Fetch(criteria);
        }

        public static ApplicationPermissionList GetByCriteria(ApplicationPermissionCriteria criteria)
        {
          return  new ApplicationPermissionList().DataPortal_Fetch(criteria);
//            return DataPortal.Fetch<ApplicationPermissionList>(criteria);
        }

        public static ApplicationPermissionList GetAll()
        {
          return  new ApplicationPermissionList().DataPortal_Fetch(new ApplicationPermissionCriteria());
            //return DataPortal.Fetch<ApplicationPermissionList>(new ApplicationPermissionCriteria());
        }

        #endregion

        #region Asynchronous Factory Methods
     

     

     

     

     

     

     

     

     
 
        #endregion

        #region DataPortal partial methods

        /// <summary>
        /// CodeSmith generated stub method that is called when creating the child <see cref="ApplicationPermission"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object creation should proceed.</param>
        partial void OnCreating(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="ApplicationPermission"/> object has been created. 
        /// </summary>
        partial void OnCreated();

        /// <summary>
        /// CodeSmith generated stub method that is called when fetching the child <see cref="ApplicationPermission"/> object. 
        /// </summary>
        /// <param name="criteria"><see cref="ApplicationPermissionCriteria"/> object containing the criteria of the object to fetch.</param>
        /// <param name="cancel">Value returned from the method indicating whether the object fetching should proceed.</param>
        partial void OnFetching(ApplicationPermissionCriteria criteria, ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="ApplicationPermission"/> object has been fetched. 
        /// </summary>
        partial void OnFetched();

        /// <summary>
        /// CodeSmith generated stub method that is called when mapping the child <see cref="ApplicationPermission"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object mapping should proceed.</param>
        partial void OnMapping(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called when mapping the child <see cref="ApplicationPermission"/> object. 
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="cancel">Value returned from the method indicating whether the object mapping should proceed.</param>
        //partial void OnMapping(SafeDataReader reader, ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="ApplicationPermission"/> object has been mapped. 
        /// </summary>
        partial void OnMapped();

        /// <summary>
        /// CodeSmith generated stub method that is called when updating the <see cref="ApplicationPermission"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object creation should proceed.</param>
        partial void OnUpdating(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the <see cref="ApplicationPermission"/> object has been updated. 
        /// </summary>
        partial void OnUpdated();
       // partial void OnAddNewCore(ref ApplicationPermission item, ref bool cancel);

        #endregion

    }
}