//------------------------------------------------------------------------------
// <autogenerated>
//     
//       Changes to this template will not be lost.
//
//     Template: DTOList.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;

 
namespace CFMData
{    
    /// <summary>
    /// The ApplicationRoleList class is a CSLA editable root class.  See CSLA documentation for a more detailed description.
    /// </summary>
    public partial class ApplicationRoleListDTO
    {
    }
}