//------------------------------------------------------------------------------
// <autogenerated>
//     
//       Changes to this template will not be lost.
//
//     Template: EditableRootList.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using Dapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace CFMData
{
    /// <summary>
    /// The ApplicationRoleList class is a CSLA editable root list class collection of <see cref="ApplicationRole"/> objects.  See CSLA documentation for a more detailed description.
    /// </summary>
    /// <returns></returns>
    public partial class ApplicationRoleList
    {
        public static ApplicationRoleList ValidateRole(string roleName, int? applicationRoleID)
        {
            return new ApplicationRoleList().DataPortal_Fetch(roleName, applicationRoleID);
        }

        private ApplicationRoleList DataPortal_Fetch(string roleName, int? applicationRoleID)
        {
            bool cancel = false;

            if (cancel) return null;

            //RaiseListChangedEvents = false;

            // Fetch Child objects.
            using (var connection = new SqlConnection(ADOHelper.ConnectionString))
            {
                connection.Open();
                using (var command = new SqlCommand("[dbo].[spCFM_ApplicationRole_Validate]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;

                    command.Parameters.AddWithValue("@p_ApplicationRoleName", roleName);
                    if (applicationRoleID.HasValue)
                    {
                        command.Parameters.AddWithValue("@p_applicationRoleID", applicationRoleID.Value);
                    }
                    using (var reader = command.ExecuteReader())
                    {

                        if (reader.Read())
                        {
                            var rowParser = reader.GetRowParser<ApplicationRole>();
                            do
                            {

                                this.Add(ApplicationRole.GetApplicationRole(rowParser, reader));
                            } while (reader.Read());
                        }
                        return this;
                    }
                }
            }
        }

    }
}