//------------------------------------------------------------------------------
// <autogenerated>
//     
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'BankTransactionList.cs'.
//
//     Template: EditableRootList.Generated.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
 
namespace CFMData
{
    [Serializable]
    public partial class BankTransactionList : List< BankTransaction>
    {    
        private List<BankTransactionDTO> _currentDto =null; 
        public List<BankTransactionDTO> CurrentDTO
        {
            get 
            {
                if (_currentDto==null)
                {
                    _currentDto=new List<BankTransactionDTO>();
                    foreach (BankTransaction entity in this)
                    {
                        _currentDto.Add(entity.CurrentDTO);
                    }
                }
                return _currentDto;
			}
            
        }
        #region Contructor(s)

        public BankTransactionList()
        { 
       //     AllowNew = true;
        }

        #endregion

       

        #region Synchronous Factory Methods 

        /// <summary>
        /// Creates a new object of type <see cref="BankTransactionList"/>. 
        /// </summary>
        /// <returns>Returns a newly instantiated collection of type <see cref="BankTransactionList"/>.</returns>
        public static BankTransactionList NewList()
        {
            return new BankTransactionList();
        }      

        /// <summary>
        /// Returns a <see cref="BankTransactionList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="bankTransactionID">No additional detail available.</param>
        /// <returns>A <see cref="BankTransactionList"/> object of the specified criteria.</returns>
        public static BankTransactionList GetByBankTransactionID(System.Int32 bankTransactionID)
        {
            var criteria = new BankTransactionCriteria{BankTransactionID = bankTransactionID};
            
            
          return  new BankTransactionList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="BankTransactionList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="createdBy">No additional detail available.</param>
        /// <returns>A <see cref="BankTransactionList"/> object of the specified criteria.</returns>
        public static BankTransactionList GetByCreatedBy(System.Int32 createdBy)
        {
            var criteria = new BankTransactionCriteria{CreatedBy = createdBy};
            
            
          return  new BankTransactionList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="BankTransactionList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="bankAccountID">No additional detail available.</param>
        /// <returns>A <see cref="BankTransactionList"/> object of the specified criteria.</returns>
        public static BankTransactionList GetByBankAccountID(System.Int32? bankAccountID)
        {
            var criteria = new BankTransactionCriteria{};
                            if(bankAccountID.HasValue) criteria.BankAccountID = bankAccountID.Value;
            
          return  new BankTransactionList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="BankTransactionList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="updatedBy">No additional detail available.</param>
        /// <returns>A <see cref="BankTransactionList"/> object of the specified criteria.</returns>
        public static BankTransactionList GetByUpdatedBy(System.Int32? updatedBy)
        {
            var criteria = new BankTransactionCriteria{};
                            if(updatedBy.HasValue) criteria.UpdatedBy = updatedBy.Value;
            
          return  new BankTransactionList().DataPortal_Fetch(criteria);
        }

        public static BankTransactionList GetByCriteria(BankTransactionCriteria criteria)
        {
          return  new BankTransactionList().DataPortal_Fetch(criteria);
//            return DataPortal.Fetch<BankTransactionList>(criteria);
        }

        public static BankTransactionList GetAll()
        {
          return  new BankTransactionList().DataPortal_Fetch(new BankTransactionCriteria());
            //return DataPortal.Fetch<BankTransactionList>(new BankTransactionCriteria());
        }

        #endregion

        #region Asynchronous Factory Methods
     

     

     

     

     
 
        #endregion

        #region DataPortal partial methods

        /// <summary>
        /// CodeSmith generated stub method that is called when creating the child <see cref="BankTransaction"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object creation should proceed.</param>
        partial void OnCreating(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="BankTransaction"/> object has been created. 
        /// </summary>
        partial void OnCreated();

        /// <summary>
        /// CodeSmith generated stub method that is called when fetching the child <see cref="BankTransaction"/> object. 
        /// </summary>
        /// <param name="criteria"><see cref="BankTransactionCriteria"/> object containing the criteria of the object to fetch.</param>
        /// <param name="cancel">Value returned from the method indicating whether the object fetching should proceed.</param>
        partial void OnFetching(BankTransactionCriteria criteria, ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="BankTransaction"/> object has been fetched. 
        /// </summary>
        partial void OnFetched();

        /// <summary>
        /// CodeSmith generated stub method that is called when mapping the child <see cref="BankTransaction"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object mapping should proceed.</param>
        partial void OnMapping(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called when mapping the child <see cref="BankTransaction"/> object. 
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="cancel">Value returned from the method indicating whether the object mapping should proceed.</param>
        //partial void OnMapping(SafeDataReader reader, ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="BankTransaction"/> object has been mapped. 
        /// </summary>
        partial void OnMapped();

        /// <summary>
        /// CodeSmith generated stub method that is called when updating the <see cref="BankTransaction"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object creation should proceed.</param>
        partial void OnUpdating(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the <see cref="BankTransaction"/> object has been updated. 
        /// </summary>
        partial void OnUpdated();
       // partial void OnAddNewCore(ref BankTransaction item, ref bool cancel);

        #endregion

    }
}