//------------------------------------------------------------------------------
// <autogenerated>
//     
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'BudgetList.cs'.
//
//     Template: EditableRootList.Generated.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
 
namespace CFMData
{
    [Serializable]
    public partial class BudgetList : List< Budget>
    {    
        private List<BudgetDTO> _currentDto =null; 
        public List<BudgetDTO> CurrentDTO
        {
            get 
            {
                if (_currentDto==null)
                {
                    _currentDto=new List<BudgetDTO>();
                    foreach (Budget entity in this)
                    {
                        _currentDto.Add(entity.CurrentDTO);
                    }
                }
                return _currentDto;
			}
            
        }
        #region Contructor(s)

        public BudgetList()
        { 
       //     AllowNew = true;
        }

        #endregion

       

        #region Synchronous Factory Methods 

        /// <summary>
        /// Creates a new object of type <see cref="BudgetList"/>. 
        /// </summary>
        /// <returns>Returns a newly instantiated collection of type <see cref="BudgetList"/>.</returns>
        public static BudgetList NewList()
        {
            return new BudgetList();
        }      

        /// <summary>
        /// Returns a <see cref="BudgetList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="budgetID">No additional detail available.</param>
        /// <returns>A <see cref="BudgetList"/> object of the specified criteria.</returns>
        public static BudgetList GetByBudgetID(System.Int32 budgetID)
        {
            var criteria = new BudgetCriteria{BudgetID = budgetID};
            
            
          return  new BudgetList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="BudgetList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="createdBy">No additional detail available.</param>
        /// <returns>A <see cref="BudgetList"/> object of the specified criteria.</returns>
        public static BudgetList GetByCreatedBy(System.Int32 createdBy)
        {
            var criteria = new BudgetCriteria{CreatedBy = createdBy};
            
            
          return  new BudgetList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="BudgetList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="budgetTypeID">No additional detail available.</param>
        /// <returns>A <see cref="BudgetList"/> object of the specified criteria.</returns>
        public static BudgetList GetByBudgetTypeID(System.Int32 budgetTypeID)
        {
            var criteria = new BudgetCriteria{BudgetTypeID = budgetTypeID};
            
            
          return  new BudgetList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="BudgetList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="clientID">No additional detail available.</param>
        /// <returns>A <see cref="BudgetList"/> object of the specified criteria.</returns>
        public static BudgetList GetByClientID(System.Int32? clientID)
        {
            var criteria = new BudgetCriteria{};
                            if(clientID.HasValue) criteria.ClientID = clientID.Value;
            
          return  new BudgetList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="BudgetList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="homeID">No additional detail available.</param>
        /// <returns>A <see cref="BudgetList"/> object of the specified criteria.</returns>
        public static BudgetList GetByHomeID(System.Int32? homeID)
        {
            var criteria = new BudgetCriteria{};
                            if(homeID.HasValue) criteria.HomeID = homeID.Value;
            
          return  new BudgetList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="BudgetList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="updatedBy">No additional detail available.</param>
        /// <returns>A <see cref="BudgetList"/> object of the specified criteria.</returns>
        public static BudgetList GetByUpdatedBy(System.Int32? updatedBy)
        {
            var criteria = new BudgetCriteria{};
                            if(updatedBy.HasValue) criteria.UpdatedBy = updatedBy.Value;
            
          return  new BudgetList().DataPortal_Fetch(criteria);
        }

        public static BudgetList GetByCriteria(BudgetCriteria criteria)
        {
          return  new BudgetList().DataPortal_Fetch(criteria);
//            return DataPortal.Fetch<BudgetList>(criteria);
        }

        public static BudgetList GetAll()
        {
          return  new BudgetList().DataPortal_Fetch(new BudgetCriteria());
            //return DataPortal.Fetch<BudgetList>(new BudgetCriteria());
        }

        #endregion

        #region Asynchronous Factory Methods
     

     

     

     

     

     

     
 
        #endregion

        #region DataPortal partial methods

        /// <summary>
        /// CodeSmith generated stub method that is called when creating the child <see cref="Budget"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object creation should proceed.</param>
        partial void OnCreating(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="Budget"/> object has been created. 
        /// </summary>
        partial void OnCreated();

        /// <summary>
        /// CodeSmith generated stub method that is called when fetching the child <see cref="Budget"/> object. 
        /// </summary>
        /// <param name="criteria"><see cref="BudgetCriteria"/> object containing the criteria of the object to fetch.</param>
        /// <param name="cancel">Value returned from the method indicating whether the object fetching should proceed.</param>
        partial void OnFetching(BudgetCriteria criteria, ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="Budget"/> object has been fetched. 
        /// </summary>
        partial void OnFetched();

        /// <summary>
        /// CodeSmith generated stub method that is called when mapping the child <see cref="Budget"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object mapping should proceed.</param>
        partial void OnMapping(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called when mapping the child <see cref="Budget"/> object. 
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="cancel">Value returned from the method indicating whether the object mapping should proceed.</param>
        //partial void OnMapping(SafeDataReader reader, ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="Budget"/> object has been mapped. 
        /// </summary>
        partial void OnMapped();

        /// <summary>
        /// CodeSmith generated stub method that is called when updating the <see cref="Budget"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object creation should proceed.</param>
        partial void OnUpdating(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the <see cref="Budget"/> object has been updated. 
        /// </summary>
        partial void OnUpdated();
       // partial void OnAddNewCore(ref Budget item, ref bool cancel);

        #endregion

    }
}