//------------------------------------------------------------------------------
// <autogenerated>
//     
//       Changes to this template will not be lost.
//
//     Template: EditableRootList.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
 

namespace CFMData
{
    /// <summary>
    /// The BusinessAreaList class is a CSLA editable root list class collection of <see cref="BusinessArea"/> objects.  See CSLA documentation for a more detailed description.
    /// </summary>
    /// <returns></returns>
    public partial class BusinessAreaList
    {
 
    }
}