//------------------------------------------------------------------------------
// <autogenerated>
//     
//       Changes to this template will not be lost.
//
//     Template: EditableRootList.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using Dapper;


namespace CFMData
{
    /// <summary>
    /// The EmailQueueList class is a CSLA editable root list class collection of <see cref="EmailQueue"/> objects.  See CSLA documentation for a more detailed description.
    /// </summary>
    /// <returns></returns>
    public partial class EmailQueueList
    {
    public static EmailQueueList GetPending()
    {
        return new EmailQueueList().GetPendingInternal();
        //return DataPortal.Fetch<EmailQueueList>(new EmailQueueCriteria());
    }
    private EmailQueueList GetPendingInternal()
    {
        bool cancel = false;

        if (cancel) return null;

        //RaiseListChangedEvents = false;

        // Fetch Child objects.
        using (var connection = new SqlConnection(ADOHelper.ConnectionString))
        {
            connection.Open();
            using (var command = new SqlCommand("[dbo].[spCFM_EmailQueue_SelectPending]", connection))
            {
                command.CommandType = CommandType.StoredProcedure;

                using (var reader = command.ExecuteReader())
                {

                    if (reader.Read())
                    {
                        var rowParser = reader.GetRowParser<CFMData.EmailQueue>();
                        do
                        {

                            this.Add(CFMData.EmailQueue.GetEmailQueue(rowParser, reader));
                        } while (reader.Read());
                    }
                    OnFetched();
                    return this;
                }
            }
        }

        //RaiseListChangedEvents = true;


    }
  }
}