--region Drop Existing Procedures

SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO
PRINT N'Dropping spCFM_EmailQueue_Select'
GO
IF EXISTS(SELECT 1 FROM fn_listextendedproperty (NULL, 'SCHEMA', 'dbo', 'PROCEDURE', 'spCFM_EmailQueue_Select', default, default) WHERE name = 'CustomProcedure' and value = '1')
BEGIN
    RAISERROR ('The procedure spCFM_EmailQueue_Select has an Extended Property "CustomProcedure" which means is has been customized. Please review and remove the property if you wish to drop the procedure.',16,1)
    INSERT INTO #tmpErrors (Error) SELECT 1
END
GO

IF OBJECT_ID(N'spCFM_EmailQueue_Select') IS NOT NULL
	DROP PROCEDURE spCFM_EmailQueue_Select

GO
IF @@ERROR!=0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO

IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO

IF @@TRANCOUNT>0 BEGIN
PRINT 'The stored procedure drop has succeeded'
COMMIT TRANSACTION
END
ELSE PRINT 'The stored procedure drop has failed'
GO

DROP TABLE #tmpErrors
GO
--endregion

GO

--region [dbo].[spCFM_EmailQueue_Select]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   prady using CodeSmith: v7.1.0, CSLA Templates: v4.0.0.0, CSLA Framework: v4.3.10
-- Procedure Name: [dbo].[spCFM_EmailQueue_Select]
------------------------------------------------------------------------------------------------------------------------

SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION
GO

PRINT N'Creating [dbo].[spCFM_EmailQueue_Select]'
GO

IF EXISTS(SELECT 1 FROM fn_listextendedproperty (NULL, 'SCHEMA', 'dbo', 'PROCEDURE', 'spCFM_EmailQueue_Select', default, default) WHERE name = 'CustomProcedure' and value = '1')
    BEGIN
        RAISERROR ('The procedure [dbo].[spCFM_EmailQueue_Select] has an Extended Property "CustomProcedure" which means is has been customized. Please review and remove the property if you wish to create the stored procedure.',16,1)
        INSERT INTO #tmpErrors (Error) SELECT 1
    END
GO

CREATE PROCEDURE [dbo].[spCFM_EmailQueue_Select]
	@p_EmailQueueID int = NULL,
	@p_MailingTemplateID int = NULL,
	@p_MailingTemplateIDHasValue BIT = 0,
	@p_SendTo varchar(255) = NULL,
	@p_SendToHasValue BIT = 0,
	@p_MailingText nvarchar(4000) = NULL,
	@p_MailingTextHasValue BIT = 0,
	@p_MailingSubject varchar(1024) = NULL,
	@p_MailingSubjectHasValue BIT = 0,
	@p_MailingFrom varchar(50) = NULL,
	@p_MailingFromHasValue BIT = 0,
	@p_RequestedDate datetime = NULL,
	@p_ProcessedDate datetime = NULL,
	@p_ProcessedDateHasValue BIT = 0,
	@p_ProcessResult varchar(max) = NULL,
	@p_ProcessResultHasValue BIT = 0
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[EmailQueueID],
	[MailingTemplateID],
	[SendTo],
	[MailingText],
	[MailingSubject],
	[MailingFrom],
	[RequestedDate],
	[ProcessedDate],
	[ProcessResult]
FROM
    [dbo].[EmailQueue]
WHERE
	([EmailQueueID] = @p_EmailQueueID OR @p_EmailQueueID IS NULL)
	AND ([MailingTemplateID] = @p_MailingTemplateID OR (@p_MailingTemplateID IS NULL AND @p_MailingTemplateIDHasValue = 0))
	AND ([SendTo] = @p_SendTo OR (@p_SendTo IS NULL AND @p_SendToHasValue = 0))
	AND ([MailingText] = @p_MailingText OR (@p_MailingText IS NULL AND @p_MailingTextHasValue = 0))
	AND ([MailingSubject] = @p_MailingSubject OR (@p_MailingSubject IS NULL AND @p_MailingSubjectHasValue = 0))
	AND ([MailingFrom] = @p_MailingFrom OR (@p_MailingFrom IS NULL AND @p_MailingFromHasValue = 0))
	AND ([RequestedDate] = @p_RequestedDate OR @p_RequestedDate IS NULL)
	AND ([ProcessedDate] = @p_ProcessedDate OR (@p_ProcessedDate IS NULL AND @p_ProcessedDateHasValue = 0))
	AND ([ProcessResult] = @p_ProcessResult OR (@p_ProcessResult IS NULL AND @p_ProcessResultHasValue = 0))

GO
IF @@ERROR!=0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO

IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT 'Stored procedure creation succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT 'Stored procedure creation failed.'
GO
DROP TABLE #tmpErrors
GO

--endregion

GO

