//------------------------------------------------------------------------------
// <autogenerated>
//     
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'EmailQueueList.cs'.
//
//     Template: EditableRootList.DataAccess.StoredProcedures.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.SqlClient;
using Dapper;
namespace CFMData
{
    public partial class EmailQueueList
    {
        
        private EmailQueueList DataPortal_Fetch(EmailQueueCriteria criteria)
        {
            bool cancel = false;
            OnFetching(criteria, ref cancel);
            if (cancel) return null;

            //RaiseListChangedEvents = false;

            // Fetch Child objects.
            using (var connection = new SqlConnection(ADOHelper.ConnectionString))
            {
                connection.Open();
                using (var command = new SqlCommand("[dbo].[spCFM_EmailQueue_Select]", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
		
                    command.Parameters.AddRange(ADOHelper.SqlParameters(criteria.StateBag));
                    command.Parameters.AddWithValue("@p_MailingTemplateIDHasValue", criteria.MailingTemplateIDHasValue);
                command.Parameters.AddWithValue("@p_SendToHasValue", criteria.SendToHasValue);
                command.Parameters.AddWithValue("@p_MailingTextHasValue", criteria.MailingTextHasValue);
                command.Parameters.AddWithValue("@p_MailingSubjectHasValue", criteria.MailingSubjectHasValue);
                command.Parameters.AddWithValue("@p_MailingFromHasValue", criteria.MailingFromHasValue);
                command.Parameters.AddWithValue("@p_ProcessedDateHasValue", criteria.ProcessedDateHasValue);
                command.Parameters.AddWithValue("@p_ProcessResultHasValue", criteria.ProcessResultHasValue);
                    using(var reader = command.ExecuteReader())
                    {
						
                        if(reader.Read())
                        {
                           var rowParser = reader.GetRowParser<CFMData.EmailQueue>();
                           do
                           {
								
                              this.Add(CFMData.EmailQueue.GetEmailQueue(rowParser, reader));
                           }while(reader.Read());
                        }
						OnFetched();
                        return this;
                    }
                }
            }

            //RaiseListChangedEvents = true;

            
        }

        //[Transactional(TransactionalTypes.TransactionScope)]
        protected   void DataPortal_Update()
        {
            bool cancel = false;
            OnUpdating(ref cancel);
            if (cancel) return;

          

           

            for (int index = 0; index < this.Count; index++)
            {
                this[index] = this[index].Save();
            }

           

            OnUpdated();
         }
    }
}
