//------------------------------------------------------------------------------
// <autogenerated>
//     
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'SystemRoleList.cs'.
//
//     Template: EditableRootList.Generated.cst
//     
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
 
namespace CFMData
{
    [Serializable]
    public partial class SystemRoleList : List< SystemRole>
    {    
        private List<SystemRoleDTO> _currentDto =null; 
        public List<SystemRoleDTO> CurrentDTO
        {
            get 
            {
                if (_currentDto==null)
                {
                    _currentDto=new List<SystemRoleDTO>();
                    foreach (SystemRole entity in this)
                    {
                        _currentDto.Add(entity.CurrentDTO);
                    }
                }
                return _currentDto;
			}
            
        }
        #region Contructor(s)

        public SystemRoleList()
        { 
       //     AllowNew = true;
        }

        #endregion

       

        #region Synchronous Factory Methods 

        /// <summary>
        /// Creates a new object of type <see cref="SystemRoleList"/>. 
        /// </summary>
        /// <returns>Returns a newly instantiated collection of type <see cref="SystemRoleList"/>.</returns>
        public static SystemRoleList NewList()
        {
            return new SystemRoleList();
        }      

        /// <summary>
        /// Returns a <see cref="SystemRoleList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="systemRoleID">No additional detail available.</param>
        /// <returns>A <see cref="SystemRoleList"/> object of the specified criteria.</returns>
        public static SystemRoleList GetBySystemRoleID(System.Int32 systemRoleID)
        {
            var criteria = new SystemRoleCriteria{SystemRoleID = systemRoleID};
            
            
          return  new SystemRoleList().DataPortal_Fetch(criteria);
        }

        /// <summary>
        /// Returns a <see cref="SystemRoleList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="systemRoleTypeID">No additional detail available.</param>
        /// <returns>A <see cref="SystemRoleList"/> object of the specified criteria.</returns>
        public static SystemRoleList GetBySystemRoleTypeID(System.Int32 systemRoleTypeID)
        {
            var criteria = new SystemRoleCriteria{SystemRoleTypeID = systemRoleTypeID};
            
            
          return  new SystemRoleList().DataPortal_Fetch(criteria);
        }

        public static SystemRoleList GetByCriteria(SystemRoleCriteria criteria)
        {
          return  new SystemRoleList().DataPortal_Fetch(criteria);
//            return DataPortal.Fetch<SystemRoleList>(criteria);
        }

        public static SystemRoleList GetAll()
        {
          return  new SystemRoleList().DataPortal_Fetch(new SystemRoleCriteria());
            //return DataPortal.Fetch<SystemRoleList>(new SystemRoleCriteria());
        }

        #endregion

        #region Asynchronous Factory Methods
     

     

     
 
        #endregion

        #region DataPortal partial methods

        /// <summary>
        /// CodeSmith generated stub method that is called when creating the child <see cref="SystemRole"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object creation should proceed.</param>
        partial void OnCreating(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="SystemRole"/> object has been created. 
        /// </summary>
        partial void OnCreated();

        /// <summary>
        /// CodeSmith generated stub method that is called when fetching the child <see cref="SystemRole"/> object. 
        /// </summary>
        /// <param name="criteria"><see cref="SystemRoleCriteria"/> object containing the criteria of the object to fetch.</param>
        /// <param name="cancel">Value returned from the method indicating whether the object fetching should proceed.</param>
        partial void OnFetching(SystemRoleCriteria criteria, ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="SystemRole"/> object has been fetched. 
        /// </summary>
        partial void OnFetched();

        /// <summary>
        /// CodeSmith generated stub method that is called when mapping the child <see cref="SystemRole"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object mapping should proceed.</param>
        partial void OnMapping(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called when mapping the child <see cref="SystemRole"/> object. 
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="cancel">Value returned from the method indicating whether the object mapping should proceed.</param>
        //partial void OnMapping(SafeDataReader reader, ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="SystemRole"/> object has been mapped. 
        /// </summary>
        partial void OnMapped();

        /// <summary>
        /// CodeSmith generated stub method that is called when updating the <see cref="SystemRole"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object creation should proceed.</param>
        partial void OnUpdating(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the <see cref="SystemRole"/> object has been updated. 
        /// </summary>
        partial void OnUpdated();
       // partial void OnAddNewCore(ref SystemRole item, ref bool cancel);

        #endregion

    }
}